### PR TITLE
Fix: Update to actions template to match the current repo

### PR DESCRIPTION
**Pull request by brian-intel**
chore(deps): Update EdgeX Dependencies to 3.1.0

## PR Checklist

- [x] Added label to the Pull Request for easier discoverability and search
- [x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-vending/blob/main/.github/CONTRIBUTING.md
- [x] Every commit is a single defect fix and does not mix feature addition or changes
- [ ] Unit Tests have been added for new changes
- [x] Updated Documentation as relevant to the changes
- [x] All commented out code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with repository license and clearly outlined the added dependency.
- [ ] PR change contains code related to security
- [ ] PR introduces changes that breaks compatibility with other modules (If YES, please provide details below)

## What are you changing?

Update github actions to match the current repo

## Issue this PR will close

None

## Test Instructions if applicable

1. Start a new PR for a full run
2. Run each action manually
3. Check main readme badges

### CODE REVIEW

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by jim-wang-intel** [comment]
@brian-intel the commit looks a bit weird: it contains merging stuffs from other earlier commits

**Comment by brian-intel** [comment]
@jim-wang-intel I think these are the 3.1 changes from earlier. Let me rebase and update.

**Review by marcpfuller — APPROVED** [review]
LGTM

**Pull request merged**
